---
kind: pipeline
type: docker
name: default

steps:
  - name: test package
    image: python:3.8
    commands:
      - pip install  pipenv
      - pipenv install --system --dev
      - pytest -v

  - name: publish to pypi
    image: plugins/pypi
    settings:
      username: __token__
      password: 
        from_secret: pypi_token
      distribution:
        - bdist_wheel
    when:
      event:
        - tag