---
kind: pipeline
type: docker
name: default

steps:
  - name: test package
    image: python:3.8
    commands:
      - pip install  pipenv
      - pipenv install --system --dev
      - pytest -v
  
  - name: build package
    