image: python:3.7

before_script:
  - pip install pipenv setuptools twine
  - pipenv install --system

stages:
  - test
  - staging
  - deploy

test:
  stage: test
  script:
    - python -m unittest

deploy_testpypi:
  stage: staging
  script:
    - python setup.py sdist bdist_wheel
    - twine upload -r testpypi dist/*
  only:
    - tags

deploy_pypi:
  stage: deploy
  script:
    - python setup.py sdist bdist_wheel
    - twine upload dist/*
  only:
    - manual